Repository openshift/apiserver-library-go, pull requests merged in 2019-11, with the labels that each got.

#8 Bug 1768877: Fix image lookup for ReplicaSets and DaemonSets in app group
  pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#9 Bug 1757553: Add service with network.openshift.io group as escalating
  pkg/authorization/scope/converter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#10 Bug 1757553: Escalating external ip 1.17.0 beta.2
  pkg/authorization/scope/converter.go
Labels: bugzilla/valid-bug, size/XS

#11 Bug 1723248: do not wrap not found when getting a pod
  pkg/securitycontextconstraints/sccadmission/scc_exec.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
