Repository openshift/apiserver-library-go, pull requests merged in 2021-08, with the labels that each got.

#55 Bug 1981775: fix Deployment creates a huge number of ReplicaSets
  pkg/admission/imagepolicy/accept.go
  pkg/admission/imagepolicy/imagepolicy.go
  pkg/admission/imagepolicy/imagepolicy_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#56 Bug 1981784: fix Deployment creates a huge number of ReplicaSets
  pkg/admission/imagepolicy/accept.go
  pkg/admission/imagepolicy/imagepolicy.go
  pkg/admission/imagepolicy/imagepolicy_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#60 Bug 1996646: pkg/securitycontextconstraints: fix points groups
  pkg/securitycontextconstraints/sccmatching/matcher.go
  pkg/securitycontextconstraints/util/sort/byrestrictions.go
  pkg/securitycontextconstraints/util/sort/byrestrictions_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#61 Bug 1986003: bump(k8s.io/*): v0.22.1
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
