Repository openshift/apiserver-library-go, pull requests merged in 2021-04, with the labels that each got.

#41 Remove tnozicka from OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#47 Bug 1934400: scc-admission: don't apply defaultAllowPrivilegeEscalation:false when container is privileged
  pkg/securitycontextconstraints/sccmatching/provider.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#48 Bug 1923847: labelselector: fix empty value parsing
  pkg/labelselector/labelselector.go
  pkg/labelselector/labelselector_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
