Repository openshift/apiserver-library-go, pull requests merged in 2023-06, with the labels that each got.

#110 securitycontextconstraints: handle ephemeral containers
  pkg/securitycontextconstraints/sccadmission/admission.go
  pkg/securitycontextconstraints/sccadmission/admission_test.go
  pkg/securitycontextconstraints/sccmatching/matcher.go
  pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/k8s.io/kubernetes/pkg/apis/core/pods/helpers.go
  vendor/k8s.io/kubernetes/pkg/fieldpath/doc.go
  vendor/k8s.io/kubernetes/pkg/fieldpath/fieldpath.go
  vendor/modules.txt
Labels: approved, lgtm

#111 [4.13] handle ephemeral containers
  pkg/securitycontextconstraints/sccadmission/admission.go
  pkg/securitycontextconstraints/sccadmission/admission_test.go
  pkg/securitycontextconstraints/sccmatching/matcher.go
  pkg/securitycontextconstraints/sccmatching/provider.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#114 [4.10] handle ephemeral containers
  go.mod
  go.sum
  pkg/securitycontextconstraints/sccadmission/admission.go
  pkg/securitycontextconstraints/sccadmission/admission_test.go
  pkg/securitycontextconstraints/sccmatching/matcher.go
  pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/k8s.io/kubernetes/pkg/apis/core/pods/helpers.go
  vendor/k8s.io/kubernetes/pkg/fieldpath/doc.go
  vendor/k8s.io/kubernetes/pkg/fieldpath/fieldpath.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#108 pkg/securitycontextconstraints/sccadmission: simplify retrieving SCCs
  pkg/securitycontextconstraints/sccadmission/admission.go
Labels: approved, lgtm

#112 [4.12] OCPBUGS-8737: handle ephemeral containers
  pkg/securitycontextconstraints/sccadmission/admission.go
  pkg/securitycontextconstraints/sccadmission/admission_test.go
  pkg/securitycontextconstraints/sccmatching/matcher.go
  pkg/securitycontextconstraints/sccmatching/provider.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
